version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=http://localhost:3000
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=123
      - MONGO_URI=mongodb://localhost:27017/
    ports:
      - '3000:3000'
